version: '2.1'
services:
  grafana-agent:
    # Contains a Dockerfile.template to support multiple architectures
    build: ./grafana
    privileged: true
    restart: always
    network_mode: host
  # other services
